name: Test build on different node versions on all platforms

on:
  schedule:
  - cron: '0 12 * * 0'

  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test-node:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Update badge text while starting build
      uses: RubbaBoy/BYOB@v1.2.1
      with:
        ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
        NAME: ${{matrix.os}}-${{matrix.node-version}}
        LABEL: "${{matrix.node-version}}"
        STATUS: "Building..."
        COLOR: grey
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get exact nodejs version
      id: node_version
      run: |
        echo "::set-output name=version::$(node --version)"

    - name: Cache bigger downloads
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/.cache
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json', 'package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json', 'package-lock.json') }}
          ${{ runner.os }}-${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

    - name: Confirm build works with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      run: npm run build

    - name: Create success badge
      if: success()
      uses: RubbaBoy/BYOB@v1.2.1
      with:
        ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
        NAME: ${{matrix.os}}-${{matrix.node-version}}
        LABEL: "${{ steps.node_version.outputs.version }}"
        STATUS: "Pass"
        COLOR: green
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create failure badge
      if: failure()
      uses: RubbaBoy/BYOB@v1.2.1
      with:
        ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
        NAME: ${{matrix.os}}-${{matrix.node-version}}
        LABEL: "${{ steps.node_version.outputs.version }}"
        STATUS: "Fail"
        COLOR: red
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
