name: Test NodeJS v10.x

on:
  schedule:
  - cron: '0 12 * * 0'

  push:
    branches: [main]

  workflow_dispatch:

jobs:

  reset-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Create success badge
        if: ${{ needs.test-node.result == 'success' }}
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
          NAME: "node-10.x"
          LABEL: "10.x"
          STATUS: "Building..."
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-node:
    needs: [reset-badge]
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x]
    runs-on: ${{ matrix.os }}
    outputs:
      gh-node-version: ${{matrix.node-version}}
      node-version: ${{ steps.node_version.outputs.version }}
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get exact nodejs version
      id: node_version
      run: |
        echo "::set-output name=version::$(node --version)"

    - name: Cache bigger downloads
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/.cache
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json', 'package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package.json', 'package-lock.json') }}
          ${{ runner.os }}-${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

    - name: Confirm build works with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      run: npm run build

  create-badges:
    needs: [test-node]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Create success badge
        if: ${{ needs.test-node.result == 'success' }}
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
          NAME: "node-${{ needs.test-node.outputs.gh-node-version }}"
          LABEL: "${{ needs.test-node.outputs.node-version }}"
          STATUS: ${{needs.test-node.result}}
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create failure badge
        if: ${{ needs.test-node.result != 'success' }}
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          ICON: https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg
          NAME: "node-${{ needs.test-node.outputs.gh-node-version }}"
          LABEL: "${{ needs.test-node.outputs.node-version }}"
          STATUS: ${{needs.test-node.result}}
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
