name: Test NodeJS v10.x

on:
  schedule:
  - cron: '0 12 * * 0'

  push:
    branches: [main]

  workflow_dispatch:

jobs:

  test-node:
    uses: ./.github/workflows/node-test.yml
    secrets: inherit
    with:
      gh-node-version: '10.x'
